kind: pipeline
type: docker
name: default

steps:
  - name: lint_dockerfile
    image: hadolint/hadolint:v1.18.0
    commands:
      - hadolint Dockerfile

  - name: build_docker
    image: plugins/docker
    settings:
      username: hsmtkk
      password:
        from_secret: docker_hub_token
      repo: hsmtkk/build_chromium_os
      tags: latest

